services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
      - redis

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
