services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BASE_URL
        value: placeholder
      - key: REDIS_HOST
        value: placeholder
      - key: REDIS_PORT
        value: placeholder
      - key: MONGO_URI
        value: placeholder
    autoDeploy: true
    regions: frankfurt

  - type: redis
    name: redis
    plan: starter

  - type: mongodb
    name: mongodb
    plan: starter
